### ISSUE TITLE
Click and 2011

### ISSUE THREAD

**Issue by socketpair** [kohler/click#237]
Recently I have discovered this cool project.

The first MAIN question - is project status. On one hand, there is good activity on github. On other — everything in internet is stopped around 2011 year. Including documentation http://www.read.cs.ucla.edu/click/.  Many projects depending on click seems died. Especially, click2netfpga. 

Please say what is happening, and what is project status now ?

**Comment by glemin** [comment]
I am working at ip6 at the moment. I hope to bring an ip6 compatible classifier next month.

Also some sort of an off topic question. Is there a document describing the coding conventions for this project? I was wondering whether variables are allowed to be given CamelCase names. And how about functions and classes? Or must everything be with underscores?

Cheers,
Glenn

**Comment by tbarbette** [comment]
There is still a lot of projects using/based on Click under development. There os some recent research papers (DoubleClick, ClickOS, FastClick, SNAP, "Lost in Network Address Translation", ...). Some authors back-ports improvements and make Pull Request from time to time, maintaining Click alive and making it evolve, for example there was the DPDK elements I recently back-ported from FastClick.

Some people still use Click in production (who exactly? From time to time, some people simply say it on Github).

The website is maintained by Eddie Kohler I think, which has not much time to give to Click lately it seems. It's true it would need a little refreshment, like generating the doc for all last elements. Maybe the wiki should be a little more publicly writeable?

Generally, when someone encounters a bug, he submits a PR, and from time to time Eddie comes and accept it. That's how Click still evolves these last years. The main problem is that nobody is paid to maintain Click, and in the academic world maintaining "use-able stuffs" doesn't give any rewards... Commercial product hide Click, and therefore do not care too much about back-porting stuffs too.

@glemin  I don't know for the documentation about language. But when in Rome, do as the romans do... If you do something like IPClassifier, copy its style and look around. I'd say what you say on another issue about variables named "p" and things like that comes from the original "in-kernel" Click where it's how things are done. In the kernel, having 3 letters for a variable name is already outstanding^^

As far as I know, everything except class name use underscores and not CamelCase.

**Comment by socketpair** [comment]
Thanks @tbarbette for explanation. I have also question about basic features of the generic router like NAT. I mean something like connection tracking / nat helpers in linux kernel. I know, there is nat for FTP. What about NAT for SIP, PPTP and some other protocols having difficulties with generic NAT ?

**Comment by glemin** [comment]
@tbarbette Thanks for the explanation. I will do as the Romans do, and use underscores everywhere ^^. Also I will keep the sort variable names for the classic things we are used too, p, errh, ... 

I will also create some doxygen documentation for the still undocumented functions. Then these elements can also have their documentation updated when a new release happens. ^^

@socketpair I don't know much about NAT but I want to help you look into the details. When I find this evening some time, I will give it a look, promised. ;-)

**Comment by kohler** [comment]
Click is currently running on hundreds of thousands of active networking devices worldwide.

**Comment by socketpair** [comment]
@kohler can you say on which devices ? just interesting :) 
@glemin yes, I want to talk about NAT.

**Comment by glemin** [comment]
@socetpair Do you know exactly which difficulties NAT has with SIP, PPTP. Has it to do with the fact that they maybe don't have a port field? Or with something else? ... . I don't know, but as I already told you, I don't know so much about NAT yet, but I am eager to learn more about it. The Linux code itself I have never inspected before, and maybe I should do that also one day. I prepare for much pain due to short variable names and so on, but I want to give it a look anyway in the future.

What is your goal as it comes to learning about NAT? Do you want to make an own switch with it (which does click NAT for you)? Or something else? You could theoretically use a Linux computer and then run Click on it, to make a switch out of it, you can use at home. However I don't know whether we still have all elements needed for that yet.

Click is an awesome software based router. If you run it in Kernel mode, it even takes over the normal Linux Kernel routing, which is epic to say the least. But also in Userlevel (that is how I run it now the entire time), it is the one of the most epic things I have ever seen and helps a lot in learning about network protocols, and maybe even developing your very own new protocols.

The click2netfpga project you referred to seems awesome. If I get it right (not sure I am though), it makes it possible to convert your Click router configuration in a hardware design. So you can use that tool to make your own hardware printed router, in stead of your software based router Click normally is (which is also very cool by the way, I like the fact that Click is so easy to use and you can turn your own Linux computer in minutes in an extremely nice software based that does exactly what you want him to do .

**Comment by socketpair** [comment]
@glemin something about Click and NAT https://pdos.csail.mit.edu/~rtm/papers/rewriter-openarch02.ps
ATTENTION. PS-file.
