### ISSUE TITLE
Question about ipfilter.cc parser

### ISSUE THREAD

**Issue by glemin** [kohler/click#242]
Hello,

I have a question about the ipfilter.cc parser. On https://github.com/kohler/click/blob/master/elements/ip/ipfilter.cc#L858 you can see the main execution part of the parser. My question is whether this is a recursive decent parser. And if yes, if the parser type could be included in the comments section. This also helps other people who might want to work further on the parser.

I also saw that in the earlier versions, the parser included a lot of function calls, with one function for each grammar rule. Now it seems that this is no longer the case, but we have a stack mechanism.

Why did we exactly leave the system by which we were calling functions out? And replaced it by a stack functions which I think seems to work in a similar way (but is less readable). When we make function we use the system stack, which seemed perfectly fine to me.

Maybe there are some good reasons, and maybe the mechanism is it is now, is not entirely a recursive decent parser anymore, but it would be nice for us the programmers if we can know a little bit more about the stack. Just a few lines, what type of stack it is, and if something special was done, why. Doesn't need to be much.

Best Regards,
Glenn Minne

**Comment by kohler** [comment]
We replaced a recursive descent parser with an iterative parser because, for some large classification programs, the recursive calls in the recursive descent parser blew out a Linux kernel stack and caused kernel crashes. (Linux kernel-thread stacks are quite limited in size.)

This explanation was provided in the commit message to the commit that added the parser, 4b613dd9b46232f1de729348719822c28c2cc1ef

In general you will find Click's commit messages more verbose than its comments. This is a software engineering choice. Programs like `git log -p FILENAME` and `git blame FILENAME` can be used to find relevant commit messages.

**Comment by glemin** [comment]
OK, great answer :-). I will also when I work on the file, write a bit about the parser in the comments section. Then we have the best of two worlds, a very comprehensible commit system, and a very comprehensible code commentary as well.
