### ISSUE TITLE
Click built over kernel 4.4 on ubuntu distribution not running in kernel mode for at least FromDevice element

### ISSUE THREAD

**Issue by Roland2014** [kohler/click#301]
We built using latest commit on master branch click for kernel 4.4 over ubuntu distribution and try to run in user mode and kernel mode.

The try has been performed with sample testdevice.click.

The result running it in user mode is ok.
But in kernel mode, while configure and compil succeeded, running testdevice.click provides the following output (last line of dmesg output):

[182248.729750] click: starting router thread pid 3155 (ffff880489978900)
[182248.730307] test-device.click:20: unknown element class 'FromDevice'
[182248.730348] Router could not be initialized!

Anybody succeeded?

**Comment by Roland2014** [comment]
To be more precise, we have noticed that some of the linuxmodule elements are skipped by make elemlist command.

Under Ubuntu 14.04.4 LTS / Linux kernel 4.2.0-27-generic
Using the latest version of click source, 

`~/click/elements$ echo "linuxmodule"  | ../bin/click-buildtool findelem -r linuxmodule -p ..
# Generated by 'click-buildtool findelem' on mardi 4 octobre 2016, 13:12:51 (UTC+0200)
../elements/linuxmodule/cyclecountaccum.cc	"../elements/linuxmodule/cyclecountaccum.hh"	CycleCountAccum-CycleCountAccum 
../elements/linuxmodule/fastudpsrc.cc	"../elements/linuxmodule/fastudpsrc.hh"	FastUDPSource-FastUDPSource 
../elements/linuxmodule/fromuserdevice.cc	"../elements/linuxmodule/fromuserdevice.hh"	FromUserDevice-FromUserDevice 
../elements/linuxmodule/rtcycles.cc	"../elements/linuxmodule/rtcycles.hh"	RTCycles-RoundTripCycleCount 
../elements/linuxmodule/schedulelinux.cc	"../elements/linuxmodule/schedulelinux.hh"	ScheduleLinux-ScheduleLinux 
../elements/linuxmodule/setcyclecount.cc	"../elements/linuxmodule/setcyclecount.hh"	SetCycleCount-SetCycleCount 
../elements/linuxmodule/touserdevice.cc	"../elements/linuxmodule/touserdevice.hh"	ToUserDevice-ToUserDevice ToUserDevice-!si ToUserDevice-!sc 
`

Under Ubuntu 14.04.1 LTS / Linux kernel 3.13.0-96-generic, 
we have the same thing too :
fromdevice/todevice/fromhost/tohost elements are eliminated !

Anybody has an idea to fix this issue ?
Thanks

**Comment by Roland2014** [comment]
A solution found there : https://atlas.hashicorp.com/amonteilhet/boxes/ubuntu-click-router

**Comment by calmisi** [comment]
Hi Roland2014,
I met the same problem, the solution you gave above is a VM boxes,
Do you know how to solve it when I want to compile in my own system, not using the VM others built.

**Comment by ronssemaxim** [comment]
Seems to me the developers disabled FromDevice, ToDevice and AnyDevice on purpuse. If you look 
at the changes made in commit 426ecaa3f9bd64111ad7009f5089112bc85afdd5, more specifically at the second to last file in fromdevice.cc, it requires the "false" element. But since false never returns true, the element does not get compiled. 

`ELEMENT_REQUIRES(AnyDevice linuxmodule false)`

Further on, because fromdevice is not compiled, anydevice also does not get compiled because it requires fromdevice, which in turn is required by todevice so it also is not being compiled.

Now on to the (partial) solution: removing the "false" requirement in fromdevice.cc will give you some errors while invoking "make install" in fromhost and tohost. So what I tried is adding the false requirement to fromhost.cc and tohost.cc while removing the false requirement in fromdevice.cc, which compiled successfully (be it with some warnings). And now fromdevice and todevice seems to be working in kernel level now, but of course now fromhost and tohost are not working anymore. 

I'm not entirely sure if this change was made on purpose or by accident, but probably the developers need to look further into this (@kohler)

**Comment by Roland2014** [comment]
Hi all,
@ronsemaxim : i've provided a solution to this previsouly providing a VM that provide an embedded workaround solution.

@calmisi: inside the VM you'll find description inside click directory with related script used. You have to reuse these scripts in your environment.

About the solution i've done:
°/ uncomment FD and TD elements
°/ use script to fix cofigure result in a way compilation work. The right and exact solution would be to modify the configure process and especially the php script that rework system C header files, but lazzy way to do it has been selected (ok this is quick and dirty)

About the motivation: it seems that a certain work amount is required for click to be usable with Kernel 4 in kernel mode. It seems that this mode is not so much used and click user mode is OK with Kernel 4.
