### ISSUE TITLE
ToDevice.u appending 14 extra bytes to packet

### ISSUE THREAD

**Issue by drbarrett** [kohler/click#409]
This seems to be a Ubuntu issue with a recent update, but I'm logging it in case anyone has found a fix.

On Ubuntu 16.04 LTS after an update on 07/25/18 ToDevice appears to write the packet correctly and I see the correct # of bytes sent in the debugger, but packets on the wire contains an extra 14 bytes of trailing garbage. This happens with method PCAP and method LINUX.

Using Socket instead of ToDevice works correctly.

**Comment by drbarrett** [comment]
Thanks for the info, this sounds like it could be it.

We're seeing it with 4.4.0-130 and 4.4.0.131 on 16.04 LTS. Guess I'll try to get things working on 18.04 to see if it solves it for us.

**Comment by piotrjurkiewicz** [comment]
So it is it.

Both these versions:

https://packages.ubuntu.com/xenial-updates/linux-image-4.4.0-130-generic
https://packages.ubuntu.com/xenial-updates/linux-image-4.4.0-131-generic

are based on 4.4.134 version of original kernel stable release. It contains the bug, as it was backported to stable release with [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.4.y&id=d9fb8cc230b2a4757e9fe4f81468f81212d4deaa) in version 4.4.133. The fix was backported with [commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.4.y&id=7666b7098d5a6fb28202540e062bc98a9c713b9e) and appeared in version 4.4.137.

So you have to wait until Ubuntu kernel maintainers rebase their packages on version 4.4.137 or higher.

**Comment by drbarrett** [comment]
I've rolled back to 4.4.0-128 for now as gcc7 in 18.04 doesn't get along with our current codebase.

**Comment by drbarrett** [comment]
In case anyone else hits it, this problem just came back on Ubuntu 18.04 with kernel 4.15.0-34. 

4.15.0-33 and earlier seem fine.
