### ISSUE TITLE
Question: print value of counter

### ISSUE THREAD

**Issue by Starefossen** [kohler/click#82]
Sorry if this is an obvious thing, I have read through the examples and documentation with no luck. But how do I print a value of a counter? Is is possible to do any if/else conditions on the counter value, eg. trigger some action when a counter reaches a certain threshold?

**Comment by girishsg24** [comment]
Hello Doctor,

I have been trying to use the Script element since a month but the console keeps complaining saying, 

Thread "click": pointer: 0x2008030270, stack: 0x3d0000                                                           
config:2: unknown element class 'Script' 

I am using the same code as you have suggested, in my .click file.
InfiniteSource -> c :: Counter(COUNT_CALL 10000 s.run) -> Discard;
s :: Script(TYPE PASSIVE, print "Something happened $(c.count)")

Could you please suggest how to deal with the issue. other elements like Print in the standard library works except for the Script element.

Thanks,
Girish
